### ISSUE TITLE
hot code loading

### ISSUE THREAD

**Issue by max22-** [cnlohr/assembly-notes#1]
Hi,
i watched your talk yesterday, it was very interesting !
On your slide about linker scripts [here](https://youtu.be/Gelf0AyVGy4?t=1942), you said it is possible to hot load c code. do you have some links to examples, or keywords  to look for on google ?
it would be a dream to do that kind of magic on the esp32 !
cheers
Maxime

**Comment by cnlohr** [comment]
We do it in the swadge project, but it is relatively poorly documented.  https://github.com/AEFeinstein/Super-2023-Swadge-FW/tree/main/tools/sandbox_test

**Comment by cnlohr** [comment]
(Closing. If I ever make a video, I make a video. If I don't, I don't.)
